export type JourneyChapter = {
  id: string;
  image: string;
  kicker: string;
  title: string;
  body: string;
  /** Film progress (0–1) at which this chapter's caption appears. */
  at: number;
  align: "left" | "right";
};

export const templeInfo = {
  nameKannada: "ಶ್ರೀ ಲಕ್ಷ್ಮೀ ವೆಂಕಟರಮಣ ದೇವಮಂದಿರ",
  nameEnglish: "Sri Lakshmi Venkataramana Devamandira",
  samajaKannada: "ಗೌಡಸಾರಸ್ವತ ಸಮಾಜ · ಶಿವಮೊಗ್ಗ",
  address: "Panchavathi Colony, Shivamogga, Karnataka 577202",
  mantraKannada: "ಓಂ ನಮೋ ವೆಂಕಟೇಶಾಯ",
  mantraEnglish: "Om Namo Venkatesaya",
} as const;

export const FILM_FRAME_COUNT = 218;

export const filmFrameSrc = (set: "d" | "m", index: number): string =>
  `/film/${set}/${String(index + 1).padStart(3, "0")}.webp`;

/**
 * Every frame of a set packed into one low-resolution sheet (~1 MB) so the
 * scrubber has complete coverage after a single request, while the ~15 MB of
 * sharp frames are still streaming. Generated by scripts/build-proxy-atlas.sh —
 * `cols` and the tile sizes must match COLS and the build() calls there.
 */
export const FILM_ATLAS = {
  cols: 12,
  d: { src: "/film/d-atlas.webp", tileWidth: 320, tileHeight: 180 },
  m: { src: "/film/m-atlas.webp", tileWidth: 180, tileHeight: 320 },
} as const;

export const filmAtlas = (set: "d" | "m") => ({
  src: FILM_ATLAS[set].src,
  cols: FILM_ATLAS.cols,
  tileWidth: FILM_ATLAS[set].tileWidth,
  tileHeight: FILM_ATLAS[set].tileHeight,
});

// `at` values are tuned to the ~21.75s scroll film (3 clips: vd_1 → vd_3 →
// new_vd): street → arch → dark threshold → lit stone hall → golden sanctum →
// deity darshan. vd_1 is the real exterior; a fadeblack (~0.26) steps inside to
// the stone hall (vd_3, lit ~0.28–0.54); a dissolve (~0.55) flows straight into
// the deity (new_vd). Keep captions off the fadeblack and dissolve.
export const journeyChapters: JourneyChapter[] = [
  {
    id: "street",
    image: "/temple/street-exterior.jpg",
    kicker: "Panchavathi Colony",
    title: "The Street",
    body: "On a quiet lane in Shivamogga the vimana rises above the palms — the first glimpse of the Lord's abode, and of the fortune He keeps for the devout.",
    at: 0,
    align: "left",
  },
  {
    id: "entrance",
    image: "/temple/entrance-facade-festival.jpg",
    kicker: "The Entrance",
    title: "Under the Arch",
    body: "Marigold garlands sway beneath the blue arch. Leave the world at the threshold — you enter the house of Lakshmi and Venkatesha.",
    at: 0.16,
    align: "right",
  },
  {
    id: "threshold",
    image: "/temple/inner-doorway-festival.jpg",
    kicker: "The Threshold",
    title: "Crossing In",
    body: "Past the festival torana the street falls silent. Sandal-smoke and lamplight receive you onto sacred ground.",
    at: 0.33,
    align: "left",
  },
  {
    id: "hall",
    image: "/temple/main-hall-sanctum.jpg",
    kicker: "The Pillared Hall",
    title: "Toward the Garbhagudi",
    body: "Down the lamp-lit hall every carved pillar leans toward the sanctum, drawing heart and eye to the Lord of the Seven Hills.",
    at: 0.45,
    align: "right",
  },
  {
    id: "sanctum",
    image: "/temple/sanctum-deity-stone-arch.jpg",
    kicker: "The Sanctum",
    title: "In Lamplight",
    body: "Within the golden arch He stands in lamplight — Srinivasa, upon whose heart Lakshmi dwells, the wellspring of all prosperity.",
    at: 0.58,
    align: "left",
  },
  {
    id: "darshan",
    image: "/temple/deity-closeup-garlands.jpg",
    kicker: "Darshan",
    title: "Garland upon Garland",
    body: "Garland upon garland at His feet. Behold Venkateshwara — refuge of this age, who turns want to abundance and sorrow to light.",
    at: 0.85,
    align: "right",
  },
];

export const finaleImage = "/temple/deity-darshan-highres.jpg";

// Devotional praise shown beneath the deity portrait at the end of the journey.
export const darshanPraise = {
  eyebrow: "ದರ್ಶನ · Darshan",
  heading: "Lord of the Seven Hills, Lakshmi upon His heart",
  paragraphs: [
    "Sri Lakshmi Venkataramana is Lord Srinivasa — Venkateshwara, the destroyer of sins — upon whose heart the Goddess Lakshmi eternally abides. In this age of Kali He is the supreme refuge of the devoted, the Lord to whom every prayer may be carried.",
    "Where Lakshmi dwells, fortune follows. To His feet devotees bring their cares and seek prosperity, health and peace; from His darshan they return bearing grace, for the Lord turns want into abundance and sorrow into light.",
    "Enshrined here by the Gowda Saraswatha Samaja of Shivamogga, the Lord receives every seeker. Bow before Him, chant His name, and let His divine blessing fill your days.",
  ],
} as const;
